# Build Pull-Request to key Branches
name: Pull Request CI with maven.

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up GraalVM JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          distribution: 'graalvm'

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Free disk space
        run: |
          sudo apt clean
          docker image ls -aq | xargs --no-run-if-empty docker rmi
          docker system prune -af
          echo "Available space"
          df -h

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Make Maven script executable
        run: chmod +x ./scripts/build_and_test.sh

      - name: Run Maven Build and Tests
        run: ./scripts/build_and_test.sh